### ISSUE TITLE
Error collecting stats, unmarshalling error

### ISSUE THREAD

**Issue by Cod3N3rd** [gesellix/couchdb-prometheus-exporter#30] opened 2018-11-19 17:41 UTC
I get the following error when running with latest version of couchdb. I have not tried with other versions.
E1119 17:31:30.366886       1 collector.go:186] Error collecting stats: error collecting couchdb stats: error unmarshalling stats: json: cannot unmarshal array into Go value of type lib.StatsResponse

**Comment by gesellix** [comment] 2018-11-19 23:53
Can you give the example at https://github.com/gesellix/couchdb-prometheus-exporter/blob/issue-30/examples/compose/docker-compose-integrationtest.yml a try?

I cannot reproduce the error message locally, can you try to find other error messages or share a bit more of your config?

**Comment by gesellix** [comment] 2019-01-07 13:37
Closing due to missing feedback - feel free to re-open providing more details.

**Closed by gesellix** 2019-01-07 13:37 UTC
