### ISSUE TITLE
Error collecting stats

### ISSUE THREAD

**Issue by OEmilius** [gesellix/couchdb-prometheus-exporter#72] opened 2020-08-11 12:42 UTC
Hello
some times alertmanager inform about node down.

./couchdb-prometheus-exporter --telemetry.address=:9984 --couchdb.uri=http://10.1.1.1:5984 --couchdb.username=admin --couchdb.password=mtr1 --logtostderr --verbosity=7 --log_dir=/tmp stderrthreshold=1

I0811 14:36:40.087946   25547 couchdb-exporter.go:273] adopted logging config: {toStderr:true alsoToStderr:false verbosity:7 stderrThreshold:2 logDir:/tmp}
I0811 14:36:40.088653   25547 couchdb-exporter.go:218] Starting exporter at ':9984' to read from CouchDB at 'http://10.1.1.1:5984'

E0811 14:45:04.107554   25547 collector.go:392] Error collecting stats: error collecting couchdb stats: error reading couchdb system stats: status 500 Internal Server Error (500): {"error":"error","reason":"{invalid_ejson,\n    {badrpc,\n        {'EXIT',\n            {{badmatch,undefined},\n             [{chttpd_misc,'-message_queues/1-fun-0-',1,\n                  [{file,\"src/chttpd_misc.erl\"},{line,446}]},\n              {lists,map,2,[{file,\"lists.erl\"},{line,1239}]},\n              {lists,map,2,[{file,\"lists.erl\"},{line,1239}]},\n              {chttpd_misc,get_stats,0,\n                  [{file,\"src/chttpd_misc.erl\"},{line,360}]},\n              {rpc,'-handle_call_call/6-fun-0-',5,\n                  [{file,\"rpc.erl\"},{line,197}]}]}}}}"}

How to collect more information?

**Comment by gesellix** [comment] 2020-08-16 20:31
Hi, can you give more details, for example about the CouchDB version, please?

**Comment by OEmilius** [comment] 2020-08-17 07:19
v. 2.1.2 .

**Comment by gesellix** [comment] 2020-08-18 15:16
I can't reproduce that error. Can you check manually, how the response to the following request looks like? Please note that the port `15984` needs to be replaced by the correct port for your CouchDB instance.

```
curl --user <admin-user>:<admin-password> http://localhost:15984/_node/_local/_system
```

**Comment by OEmilius** [comment] 2020-08-21 06:49
I can't reproduce that error too. Error happen very seldom. May be you suggeest way to locate it. log_dir=/tmp containt only 2 lines about starting exporter. Do you recomend starting flag for get more information if error will happen? 
--logtostderr --verbosity=7 --log_dir=/tmp stderrthreshold=1  -- is it enought?

**Comment by OEmilius** [comment] 2020-08-24 07:47
Error not happen 4 days. I think problem was in couchdb side - big log size 7GB. After cut log file, the error did not appear.

**Comment by gesellix** [comment] 2020-08-24 07:52
Alright, strange that the CouchDB logs such a log message. Thanks for updating! I'm going to close the issue.

**Closed by gesellix** 2020-08-24 07:52 UTC
