### ISSUE TITLE
exporter failing 

### ISSUE THREAD

**Issue by sangeethdba** [gesellix/couchdb-prometheus-exporter#106] opened 2022-01-07 17:03 UTC
```
I0107 16:53:43.277759   11181 klog_logger.go:20] "-" level="info" msg="TLS is disabled." http2=false
panic: interface conversion: interface {} is int32, not uint8

goroutine 13 [running]:
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.convertSeq(0x98b680, 0xc0003db1e0, 0xc000a7fd40)
        /home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/couch-util.go:51 +0x19f
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.convert(0x9c78e0, 0xc0005ac120, 0x1b9, 0x9c78e0, 0xc0005ac120)
        /home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/couch-util.go:69 +0x1bc
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.DecodeUpdateSeq(0xc00014e780, 0x251, 0x280, 0x96e020, 0xc000a7fab0, 0x0, 0x0)
        /home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/couch-util.go:104 +0x4d0
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.(*Exporter).collectV2(0xc00021a840, 0xc0002f47b0, 0x13f, 0xc0002f4d80, 0xc00015a000, 0x132, 0x13c, 0x0, 0x0, 0x0, ...)
        /home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/collector-v2.go:165 +0x4238
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.(*Exporter).collect(0xc00021a840, 0xc000066d20, 0x0, 0x0)
        /home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/collector.go:318 +0x1145
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.(*Exporter).Collect(0xc00021a840, 0xc000066d20)
        /home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/collector.go:421 +0x94
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:446 +0x1a2
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:538 +0xe8e
```

**Comment by go1dshtein** [comment] 2022-02-03 21:28
hello, I have same problem with couchdb 3.2.1
please help.

```
couchdb-exporter | I0203 21:21:33.877883       1 couchdb-exporter.go:273] adopted logging config: {toStderr:true alsoToStderr:false verbosity:0 stderrThreshold:2 logDir:}
couchdb-exporter | I0203 21:21:33.878376       1 couchdb-exporter.go:218] Starting exporter at '0.0.0.0:9984' to read from CouchDB at 'http://couchdb:5984'
couchdb-exporter | panic: interface conversion: interface {} is int32, not uint8
couchdb-exporter | 
couchdb-exporter | goroutine 25 [running]:
couchdb-exporter | github.com/gesellix/couchdb-prometheus-exporter/lib.convertSeq(0x7f2ee5e346e0, 0xc0003782c0, 0xc0003174d0)
couchdb-exporter | 	/app/lib/couch-util.go:51 +0x1ed
couchdb-exporter | github.com/gesellix/couchdb-prometheus-exporter/lib.convert(0x7f2ee5e6bfc0, 0xc000378ac0, 0x13e, 0x7f2ee5e6bfc0, 0xc000378ac0)
couchdb-exporter | 	/app/lib/couch-util.go:69 +0x1a0
couchdb-exporter | github.com/gesellix/couchdb-prometheus-exporter/lib.DecodeUpdateSeq(0xc0004f1340, 0x1af, 0xc0000269a6, 0x7, 0xc0002f43e8, 0xc00027d2c0, 0xa)
couchdb-exporter | 	/app/lib/couch-util.go:104 +0x4c7
couchdb-exporter | github.com/gesellix/couchdb-prometheus-exporter/lib.(*Exporter).collectV2(0xc000123900, 0xc00011b590, 0x3a, 0xc00011b9b0, 0xc0001e1080, 0x4, 0x4, 0x0, 0x0, 0x0, ...)
couchdb-exporter | 	/app/lib/collector-v2.go:118 +0x33da
couchdb-exporter | github.com/gesellix/couchdb-prometheus-exporter/lib.(*Exporter).collect(0xc000123900, 0xc0000e8cc0, 0x0, 0x0)
couchdb-exporter | 	/app/lib/collector.go:298 +0xff7
couchdb-exporter | github.com/gesellix/couchdb-prometheus-exporter/lib.(*Exporter).Collect(0xc000123900, 0xc0000e8cc0)
couchdb-exporter | 	/app/lib/collector.go:391 +0x9f
couchdb-exporter | github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
couchdb-exporter | 	/root/go/pkg/mod/github.com/prometheus/client_golang@v1.4.1/prometheus/registry.go:443 +0x19f
couchdb-exporter | created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
couchdb-exporter | 	/root/go/pkg/mod/github.com/prometheus/client_golang@v1.4.1/prometheus/registry.go:535 +0xe14
```

**Comment by gesellix** [comment] 2022-02-03 21:40
@sangeethdba can you tell whether you fixed the issue on your side before you closed it?

**Comment by sangeethdba** [comment] 2022-02-03 21:42
I donot think this exporter will work for 3.2 version

**Comment by gesellix** [comment] 2022-02-03 21:42
@go1dshtein please provide more details how you set up the exporter: the platform, operating system, Golang version in case you built it yourself. Thanks!

**Comment by gesellix** [comment] 2022-02-03 21:44
@sangeethdba ah, you might be correct, I'll have to check whether it works with V3.2

**Comment by gesellix** [comment] 2022-02-03 23:17
I couldn't reproduce the error, yet, and it seems like the exporter is compatible with CouchDB 3.2.1 when adjusting the [example setup](https://github.com/gesellix/couchdb-prometheus-exporter/blob/f1ba3b58c91d04bc6c99ad67d5ff460d9f5da0ac/examples/compose/docker-compose-integrationtest.yml) including the fix from https://github.com/apache/couchdb-docker/pull/215. Maybe the error only appears with real (bigger) databases or views?

**Comment by sangeethdba** [comment] 2022-02-04 00:22
Should we add any additional arguments to exporter to make it work with 3.2

**Comment by gesellix** [comment] 2022-02-04 17:43
@sangeethdba no, there's no additional argument required or possible to fix the issue. It's still unclear to me, under which circumstances the error occurs. I'll have to create some kind of a bigger or "older" database and trying to reach bigger update sequences.

Can you tell whether you tried to make the exporer work on older databases or on databases with many updates? Can you try to check against a fresh database?

**Comment by sangeethdba** [comment] 2022-02-04 18:07
Yes exporter was very useful and working on a 3.1 cluster.
All I had issues with 3.2 only .

Exporter failed on 3.2 cluster with no databases and also with empty
database

**Comment by sangeethdba** [comment] 2022-02-04 18:22
Small correction to my previous update.

exporter worked on 3.2 cluster which has only 2 databases and they are empty
exporter gave the below error on 3.2 cluster which has 300+ databases.


panic: interface conversion: interface {} is int32, not uint8

goroutine 36 [running]:
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.convertSeq(0x98b680,
0xc0006d1060, 0xc000246a10)
/home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/couch-util.go:51
+0x19f
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.convert(0x9c78e0,
0xc0006d1dc0, 0x1b3, 0x9c78e0, 0xc0006d1dc0)
/home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/couch-util.go:69
+0x1bc
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.DecodeUpdateSeq(0xc0001e2500,
0x24c, 0x280, 0x96e020, 0xc0002465d0, 0x0, 0x0)
/home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/couch-util.go:104
+0x4d0
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.(*Exporter).collectV2(0xc0001c7340,
0xc000299200, 0x13f, 0xc0002997d0, 0xc0002ce000, 0x133, 0x13c, 0x0, 0x0,
0x0, ...)
/home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/collector-v2.go:165
+0x4238
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.(*Exporter).collect(0xc0001c7340,
0xc000114180, 0x0, 0x0)
/home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/collector.go:318
+0x1145
github.com/gesellix/couchdb-prometheus-exporter/v30/lib.(*Exporter).Collect(0xc0001c7340,
0xc000114180)
/home/runner/work/couchdb-prometheus-exporter/couchdb-prometheus-exporter/lib/collector.go:421
+0x94
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
/home/runner/go/pkg/mod/
***@***.***/prometheus/registry.go:446 +0x1a2
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
/home/runner/go/pkg/mod/
***@***.***/prometheus/registry.go:457 +0x5ce

**Comment by sangeethdba** [comment] 2022-02-04 18:25
But on 3.1 cluster which has 300+ databses  and all go through many updates
, same exporter is working very effectively

**Comment by gesellix** [comment] 2022-02-04 18:34
That's strange and I'm not aware of anything being changed in CouchDB 3.2 causing such an issue. I'll have to find the actual request which yields the data causing the panic. I'll add more debug logs to help with this issue - are you using the exporter from one of the pre-built releases/Docker image or are you able to build it locally from the current repository sources? If so, I could put the required changes on a branch.

**Comment by sangeethdba** [comment] 2022-02-04 18:46
Used the pre built one added in this repo

**Comment by gesellix** [comment] 2022-02-04 18:47
To be more specific: we're talking about CouchDB 3.2 - and not CouchDB 3.2.1, right?

**Comment by sangeethdba** [comment] 2022-02-04 18:51
If i skip specifying databases ,exporter is working without any issues
even on 3.2 .1cluster .

Overall

exporter works very well on 3.1 cluster with --database=_all_dbs

export works very well on {version="3.2.1"}cluster *with out specifying
--database argument.* if we add even one database( tried with  _users f and
_replicator database also) for --database argument  exporter failing  .

**Comment by sangeethdba** [comment] 2022-02-04 18:51
version="3.2.1"}

**Comment by gesellix** [comment] 2022-02-04 18:54
Yeah, `--database=...` enables the code path where the panic occurs (fetching the update_seq of views), but I still wonder why e.g. a database like `_users` makes it fail. 🤔

**Comment by sangeethdba** [comment] 2022-02-04 19:06
Tried again *_users,**_replicator* ,first scrape took time (timeout error
in exporter logs E0204 19:04:44.565632   24836 collector.go:422] Error
collecting stats: error collecting couchdb stats: Get "
http://localhost:5984/": dial tcp 127.0.0.1:5984: connect: connection timed
out).   but i got the metrics in subsequent tries.

earlier tried with *_user*( errored with  no database found error). sorry
for miscommunicating.

**Comment by gesellix** [comment] 2022-02-04 20:47
I'm going to make a fix/workaround, well, let's call it a wild guess :)

**Comment by gesellix** [comment] 2022-02-05 11:10
@sangeethdba @go1dshtein I've released [v30.1.0](https://github.com/gesellix/couchdb-prometheus-exporter/releases/tag/v30.1.0), please give it a try and leave some feedback here if it resolves the issue. Thanks!

**Comment by go1dshtein** [comment] 2022-02-06 08:21
> @go1dshtein please provide more details how you set up the exporter: the platform, operating system, Golang version in case you built it yourself. Thanks!

wow! thank you very much! works perfect.

**Comment by gesellix** [comment] 2022-02-06 20:41
I'm going to close this issue, hoping that it works for @sangeethdba as well. Thanks for your patience!

**Closed by gesellix** 2022-02-06 20:41 UTC

**Comment by sangeethdba** [comment] 2022-02-06 20:43
I will test tonight and update this thread. Appreciate all your effort in
this issue.

**Comment by sangeethdba** [comment] 2022-02-07 16:50
the new version is working with 3.2.1 cluster and it is pulling all database metrics .
@gesellix  thank you so much for fixing the issue  very quickly. appreciate all your efforts of maintaining this repo.

**Comment by gesellix** [comment] 2022-02-07 17:14
Great, thanks for leaving the feedback!
